name: frebase_crud
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  get: ^4.6.6
  firebase_auth: ^5.1.1
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  #foreground a notification show korea nah ai package use korta hoi
  flutter_local_notifications: ^17.2.1  #used for foreground messaging


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

